### PR TITLE
Implement chat app with a small chess game

### PR DESCRIPTION
**Pull request by the-supernova**

### CODE REVIEW

**Comment by the-supernova** [comment]
I wanted the commit to go to a new branch not master..can you help in this @Tikam02 ?

**Comment by Tikam02** [comment]
@the-supernova let's chat in gitter

**Comment by Tikam02** [comment]
You want to commit from CLI right
so do this

   1. make a branch of your-name or just clone branch "chatbot" with this ----" git clone -b chatbot mentor
    git clone -b <branch> <remote_repo>
   2. git add .
   3. then commit it -- git commit -m "chatbot"
   4. push to the branch = " git push origin chatbot"

**Comment by Tikam02** [comment]
@the-supernova 
1.  git clone -b chess https://github.com/elynous/mentor
2.  git add . 
3. git commit -m "messages"
4. git push origin chess

if you have already pulled master branch
1. git branch -a 
2. git checkout -b <branch>   (change branch)
3. git push -u origin <branch>

**Pull request closed without merging**
